Proposal: Add motivation and Purpose
UBC-MDS/Cost_of_living_py pull request #7
Opened 2022-02-18 19:38 UTC by Arushi282

2022-02-18 21:24 UTC, voremargot requested changes
Great work! I did some editing of the proposal and made one other small suggestion. 
Before we merge please change the branch you are merging to! Right now you have selected to merge to the main branch when we should be merging to dev.

2022-02-18 21:24 UTC, voremargot commented on CONTRIBUTING.md
> +# Code of Conduct
I think you want the header to be How to contribute not code of conduct

2022-02-18 21:24 UTC, voremargot commented on Proposal.md
> +Students completing their degree spend the last 3 to 4 months of their last semester wondering: what next? Students who are looking to work after graduating especially have questions about the curren
```suggestion
Students completing their degree spend the last 3 to 4 months of their last semester wondering: what next? Students who are looking to work after graduating especially have questions about the current job market, companies and whether they will be able to afford moving to a new country or city for a job. Our dashboard aims to ease the decision making for the last factor mentioned. We aim to provide an interactive tool for users to observe the cost of living in 161 cities located across North and South America, Europe, Asia and Australia with the ability to explore different factors that affect monthly expenditures. Additionally, they will  be able to visually compare cost of living in different cities at once. Finally, we will provide visualizations for those who are looking to buy properties or see how prices compare spatially. Using this data visualization app, graduating students will be able to make more informed decisions about their life and careers after college. 
```

2022-02-18 22:56 UTC, hjw0703 approved these changes

2022-02-19 17:08 UTC, voremargot approved these changes

2022-02-19 17:12 UTC, merged